jointwt/goryon

android/settings_aar.gradle
ios/Runner/Info.plist
lib/api.dart
lib/models.dart
lib/screens/auth_widget.dart
lib/screens/login.dart
lib/screens/newtwt.dart
lib/viewmodels.dart
pubspec.lock
pubspec.yaml

- Added image upload from Gallery & Camera
- This PR is depends on https://github.com/jointwt/twtxt/pull/158

feat: Add image upload

---

pubspec.yaml

@dooven I had to bump the build number to publish a new build. I hope this is the right way to do it.

Bumped version build number to 9

---

ios/Runner/Info.plist
lib/common_widgets.dart
lib/main.dart
lib/screens/discover.dart
lib/screens/follow.dart
lib/screens/newtwt.dart
lib/screens/profile.dart
lib/screens/timeline.dart
lib/screens/videoscreen.dart
lib/widgets/common_widgets.dart
lib/widgets/twtvideoplayer.dart
pubspec.lock
pubspec.yaml

Changes
- Show profile page when avatar is tapped 
- Add video player

feat: Respond to tapping avatar + Video Player

---

lib/widgets/common_widgets.dart
pubspec.lock
pubspec.yaml

Change the avatar + username layout in twtl list

---

lib/api.dart
lib/main.dart
lib/models.dart
lib/models.g.dart
lib/screens/discover.dart
lib/screens/follow.dart
lib/screens/profile.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

- Use local time to display twts time
- Show twts when viewing user profile
- Add the the plus(+) floating action button in the profile page. This enables adding a twt for a user

Show twts in profile

---

lib/models.dart
lib/models.g.dart
lib/widgets/common_widgets.dart

This reverts commit 71eb3df1bfcfa6d50e892c5d498c066f52c958ae.

Revert "Use lowercase for the json keys"

---

lib/models.dart
lib/strings.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

Instead of building the twt text from the app, we want to use the markdown text from the api
Merge this after this PR gets merged https://github.com/jointwt/twtxt/pull/211

Use markdown from api

---

lib/api.dart
lib/models.dart
lib/screens/profile.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

- Add feature to fetch external profile
Closes #16

feat: Fetch external profile

---

lib/api.dart
lib/screens/auth_widget.dart
lib/screens/mentions.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

feat: Adding mentions screen

---

lib/screens/newtwt.dart

Thanks for sharing the source code of your project, I stumbled upon it and it was useful and inspired me.
I believe that the general user experience for editors is that the selection is the title and the URL could be entered later.
If you agree you can merge this PR as I already took care of it.

Change the url from [title](https://text) to [text]()

---

lib/api.dart
lib/screens/profile.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

Changes
- You can now click on the Followers/Following tab and view the user/feed profile by tapping the item on the list
- You can now tap on the user/feed mention and see their profile while on the twts list

fix: Fix external profile view

---

lib/main.dart
lib/screens/discover.dart
lib/screens/profile.dart
lib/screens/timeline.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
lib/widgets/twtvideoplayer.dart
pubspec.lock
pubspec.yaml

feat: Add dark mode

---

lib/api.dart
lib/models.dart
lib/models.g.dart
lib/widgets/common_widgets.dart
pubspec.yaml

- Use the subject coming from the api to build the reply
Fixes https://github.com/jointwt/goryon/issues/29
Depends on https://github.com/jointwt/twtxt/pull/223

fix: Use subject from backend

---

lib/widgets/common_widgets.dart
pubspec.yaml

feat: Add inline video player back

---

lib/api.dart
lib/form_validators.dart
lib/screens/auth_widget.dart
lib/screens/profile.dart
lib/screens/report.dart
lib/widgets/common_widgets.dart
pubspec.lock
pubspec.yaml

- Add report abuse page in the profile section ![screenshot_16](https://user-images.githubusercontent.com/15314237/95644804-5ac1c880-0a76-11eb-896e-67368fad6b6e.png)
- Add a bottom an option for users to copy the twt's link ![Peek 2020-10-09 21-29](https://user-images.githubusercontent.com/15314237/95644828-8ba1fd80-0a76-11eb-98ad-bbd7e0969c83.gif)
- Add report abuse form ![Peek 2020-10-09 21-15](https://user-images.githubusercontent.com/15314237/95644781-37971900-0a76-11eb-8c56-2b14b3d27bf7.gif)

feat: Report Abuse page

---

android/fastlane/metadata/android/en-GB/full_description.txt
android/fastlane/metadata/android/en-GB/short_description.txt
lib/api.dart
lib/models.dart
lib/models.g.dart
lib/screens/profile.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

- Able to mute/unmute user/feed 
- Added a drag icon on the bottom sheet

feat: Mute/unmute user

---

lib/screens/register.dart
pubspec.yaml

fixes: https://github.com/jointwt/goryon/issues/42

feat: Added community guideline toggle

---

lib/api.dart
lib/screens/login.dart
lib/screens/profile.dart
pubspec.yaml

- Provide an optional token & pod URI when fetching the profile
- Remove the Follow/Unfollow & report button when viewing your own profile

feat: Fix login

---

lib/screens/profile.dart
pubspec.yaml

- Add expansion tile to group profile actions
- Add pull-to-refresh profile twts
- follow/unfollows triggers a refresh to profile twts

feat: Profile ux improvements

---

lib/models.dart
lib/screens/profile.dart
lib/widgets/common_widgets.dart
pubspec.yaml

fixes #52 
Dark mode 
Light
Also removed the "Twt" button & the expansion panel

Render blockquotes in twt

---

lib/models.dart
lib/models.g.dart
lib/screens/profile.dart
lib/viewmodels.dart
pubspec.yaml

Closes #57 
When viewing a profile of a user that's not following you
When viewing a profile of a user that's following you

Added Follows/FollowedBy info in profile screen

---

lib/api.dart
lib/models.dart
lib/screens/conversation.dart
lib/screens/discover.dart
lib/screens/timeline.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

ssia
Closes #61 
Clicking the blue "reply" button will use the conversation hash as the initial text

Add Conversations

---

lib/screens/conversation.dart
lib/widgets/common_widgets.dart
pubspec.yaml

Refresh conversation after reply

---

lib/widgets/common_widgets.dart
pubspec.yaml

This way, the pull-to-refresh is enabled for list that doesnt scroll

feat: Make list always scrollable

---

lib/screens/auth_widget.dart
lib/screens/newtwt.dart
lib/viewmodels.dart
lib/widgets/common_widgets.dart
pubspec.yaml

- The Snackbar is not showing up because the build context doesnt belong the the scaffold when we call 
```
Scaffold.of(context).showSnackbar
```
- I refactored it so that the body of the widget is on its separate widget

feat: New twt refactor structure

---

README.md

doc: Add app links

---

lib/httpclient.dart
lib/main.dart
pubspec.lock
pubspec.yaml

resolves: https://github.com/jointwt/goryon/issues/72
Add app version to the user agent of request header

feat: Added user-agent to request header

---

lib/screens/newtwt.dart

This PR is a work around for the (#79) issue

Rearranged the toolbar items in the new post screen (#79)

---

lib/viewmodels.dart

Replaces http with https when users enter pod url while login (#74)
